name: overlay_popup_entry
description: A Flutter package for managing overlay popups via a controller.
version: 0.0.1
homepage: https://github.com/uxmarkowski/overlay_popup_entry
repository: https://github.com/uxmarkowski/overlay_popup_entry
license: MIT

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


